Controllers/StudentsViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS.Models;


namespace LMS.Controllers
{
    public class StudentsViewController : Controller
    {
        private readonly LmsDatabaseContext _context;
        string data;

        public StudentsViewController(LmsDatabaseContext context)
        {
            _context = context;
           
        }

        // GET: StudentsView
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var info = _context.Students.Where(x => x.Email == HttpContext.Session.GetString("UserSession"));
                return View(info);
            }
            else
            {
                return RedirectToAction("Index", "Home", null);
            }

        }
        public async Task<IActionResult> ViewTeachers()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var data = _context.Teachers.ToList();
                return View(data);
            }
            else
            {
                return RedirectToAction("Index", "Home", null);
            }
            
        }
        public async Task<IActionResult> ViewExam()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var data = _context.Exams.ToList();
                return View(data);
            }

            else
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

        public async Task<IActionResult> ViewClass()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var data = _context.Schedules.ToList();
                return View(data);
            }

            else
            {
                return RedirectToAction("Index", "Home", null);
            }

          
        }

        public async Task<IActionResult> ViewDep()
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                var data = _context.Departments.ToList();
                return View(data);
            }

            else
            {
                return RedirectToAction("Index", "Home", null);
            }

            
        }


        // GET: StudentsView/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var student = await _context.Students
                    .FirstOrDefaultAsync(m => m.SId == id);
                if (student == null)
                {
                    return NotFound();
                }

                return View(student);
            }
            else
            {
                return RedirectToAction("Index", "Home", null);
            }

        }



        // GET: StudentsView/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var student = await _context.Students.FindAsync(id);
                if (student == null)
                {
                    return NotFound();
                }
                return View(student);
            }

            else
            {
                return RedirectToAction("Index", "Home", null);
            }

        }
        // POST: StudentsView/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SId,SName,Dob,SPassword,PhoneNumber,Email")] Student student)
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                if (id != student.SId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(student);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!StudentExists(student.SId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(student);
            }
            else
            {
                return RedirectToAction("Index", "Home", null);
            }

        }

        // GET: StudentsView/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.SId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
            }
            else
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

       

    private bool StudentExists(int id)
        {
            if (HttpContext.Session.GetString("UserSession") != null)
            {
                return _context.Students.Any(e => e.SId == id);
            }
            else
            {
                return false;
            }
        }
    }
}

Views/StudentsView/Details.cshtml
@model LMS.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h1 id="top">Details</h1>

<div >
    <h4 id="top">Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dob)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.SId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/StudentsView/Edit.cshtml
@model LMS.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h1 id="top">Edit</h1>

<h4 id="top">Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SId" />
            <input type="hidden" asp-for="SName" />
            
            <div class="form-group">
                <label asp-for="Dob" class="control-label"></label>
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SPassword" class="control-label"></label>
                <input asp-for="SPassword" class="form-control" />
                <span asp-validation-for="SPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Email" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/StudentsView/Index.cshtml
@model IEnumerable<LMS.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1 id="top">DashBoard</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dob)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SPassword)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SId)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.SName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SPassword)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SId">Details</a> |
                
            </td>
        </tr>
}
    </tbody>
</table>

<div style="">
    <ul class="navbar-nav" style="text-align: center; ">
        <li><br /><br /><br /></li>

        <li>
            <a style="width:300px;  display: inline-block; background-color:black;" class="nav-link text-light" asp-area="" asp-controller="StudentsView" asp-action="ViewTeachers">View Teachers</a>
        </li>
        <li><br /></li>
        <li>
            <a style="width:300px; display: inline-block; background-color:black;" class="nav-link text-light" asp-area="" asp-controller="StudentsView" asp-action="ViewDep">Departments</a>
        </li>
        <li><br /></li>
        <li>
            <a style="width:300px; display: inline-block; background-color:black;" class="nav-link text-light" asp-area="" asp-controller="StudentsView" asp-action="ViewClass">Class Schedule</a>
        </li>
        <li><br /></li>
        <li>
            <a style="width:300px; display: inline-block; background-color:black;" class="nav-link text-light" asp-area="" asp-controller="StudentsView" asp-action="ViewExam">Exam Schedule</a>
        </li>
        <li><br /></li>
        <li>
            <a style="width:300px; display: inline-block; background-color:black;" class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="StaffLogin">Course Registration</a>
        </li>
    </ul>
</div>

Views/StudentsView/ViewClass.cshtml
@model IEnumerable<LMS.Models.Schedule>

@{
    ViewData["Title"] = "ViewClass";
}

<h1 id="top">Class Schedule</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ETime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseNameNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deptment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teacher)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EId)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.EDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ETime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseNameNavigation.CName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deptment.DId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Teacher.TId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.EId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.EId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/StudentsView/ViewDep.cshtml
@model IEnumerable<LMS.Models.Department>

@{
    ViewData["Title"] = "ViewDep";
}

<h1 id="top">Departments</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DId)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.DName)
            </td>
           
        </tr>
}
    </tbody>
</table>

Views/StudentsView/ViewExam.cshtml
@model IEnumerable<LMS.Models.Exam>

@{
    ViewData["Title"] = "ViewExam";
}

<h1 id="top">Exam Schedule</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ETime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseNameNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EId)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.EDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ETime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseNameNavigation.CName)
            </td>
           
        </tr>
}
    </tbody>
</table>

Views/StudentsView/ViewTeachers.cshtml
@model IEnumerable<LMS.Models.Teacher>

@{
    ViewData["Title"] = "ViewTeachers";
}

<h1 id="top">Teachers</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TName)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TId)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.TName)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
           
        </tr>
}
    </tbody>
</table>